package main

import (
	"fmt"
	"log"
	"net/http"

	"muxapp/internal/database"
	h "muxapp/internal/handler"
	"muxapp/internal/model"

	_ "muxapp/docs" // docs is generated by Swag CLI, you have to import it.

	httpSwagger "github.com/swaggo/http-swagger" // http-swagger middleware
)

var ResponseJson = model.ResponseJson

func main() {
	router := h.ConfigureRouter()
	database.ConnectDatabase()
	router.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		w.Write([]byte("Hello !, you can check documentation by access this url with. \n\n '.../swagger/index.html'"))
	})
	router.PathPrefix("/swagger/").Handler(httpSwagger.WrapHandler)

	// fmt.Print(
	// "\n     ______ ______ ____   __\n    /___  / ___  / __  | / /\n   ____/ / /__/ / /  | |/ /\n  /___  / ___  / /  / /  /\n ____/ / /  / / /__/ /  /\n/_____/_/  /_/______/ _/\n===========================\nrunning on port : 1323\n===========================\n\n")
	fmt.Print("======================\nRunning on port : 1323\n======================\n")
	log.Fatal(http.ListenAndServe("0.0.0.0:1323", router))
}
