// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"


// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
    Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
    swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}

const docTemplate = `
{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "dokumentasi",
    "contact": {}
  },
  "host": "192.168.100.9:1323",
  "basePath": "/api",
  "securityDefinitions": {},
  "schemes": [
    "http",
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/register": {
      "post": {
        "summary": "Register",
        "tags": [
          "auth lokal"
        ],
        "operationId": "Register",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RegisterRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "login",
        "tags": [
          "auth lokal"
        ],
        "operationId": "login",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/users": {
      "get": {
        "summary": "users",
        "tags": [
          "user lokal"
        ],
        "operationId": "users",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user/2": {
      "get": {
        "summary": "user",
        "tags": [
          "user lokal"
        ],
        "operationId": "user",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "user",
        "tags": [
          "user lokal"
        ],
        "operationId": "Putuser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/userrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/user/3": {
      "delete": {
        "summary": "user1",
        "tags": [
          "user lokal"
        ],
        "operationId": "user1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/roles": {
      "get": {
        "summary": "roles",
        "tags": [
          "role lokal"
        ],
        "operationId": "roles",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/role/1": {
      "get": {
        "summary": "role",
        "tags": [
          "role lokal"
        ],
        "operationId": "role",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "summary": "role1",
        "tags": [
          "role lokal"
        ],
        "operationId": "role1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/rolerequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "summary": "role1",
        "tags": [
          "role lokal"
        ],
        "operationId": "Deleterole1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/role": {
      "post": {
        "summary": "role",
        "tags": [
          "role lokal"
        ],
        "operationId": "Postrole",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/rolerequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/news/all/3/0": {
      "get": {
        "summary": "news page",
        "tags": [
          "news lokal"
        ],
        "operationId": "newspage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/news/1": {
      "get": {
        "summary": "news one",
        "tags": [
          "news lokal"
        ],
        "operationId": "newsone",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/news": {
      "post": {
        "summary": "news",
        "tags": [
          "news lokal"
        ],
        "operationId": "news",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "thumbnail",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "title",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "content",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/news/s/jika": {
      "get": {
        "summary": "search",
        "tags": [
          "news lokal"
        ],
        "operationId": "search",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/user_profiles": {
      "get": {
        "summary": "user profiles",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "userprofiles",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user_profile/3": {
      "get": {
        "summary": "user profile",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "userprofile",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "post": {
        "summary": "user profile",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "Postuserprofile",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/userprofilerequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "user profile1",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "Deleteuserprofile1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/user_profile/1": {
      "put": {
        "summary": "user profile1",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "userprofile1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/userprofilerequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/avatars": {
      "get": {
        "summary": "get avatar",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "getavatar",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/avatar/4": {
      "put": {
        "summary": "change avatar",
        "tags": [
          "user profile lokal"
        ],
        "operationId": "changeavatar",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/x-www-form-urlencoded"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "avatar",
            "in": "formData",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/provinsi": {
      "get": {
        "summary": "New Request",
        "tags": [
          "wilayah lokal"
        ],
        "operationId": "NewRequest",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/activity/9/0": {
      "get": {
        "summary": "activity page",
        "tags": [
          "activity lokal"
        ],
        "operationId": "activitypage",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/activity": {
      "post": {
        "summary": "activity",
        "tags": [
          "activity lokal"
        ],
        "operationId": "activity",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/activityrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/activity/5": {
      "put": {
        "summary": "activity1",
        "tags": [
          "activity lokal"
        ],
        "operationId": "activity1",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/activityrequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/activity/9": {
      "delete": {
        "summary": "activity",
        "tags": [
          "activity lokal"
        ],
        "operationId": "Deleteactivity",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": false,
            "default": "Bearer {token}",
            "type": "string"
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "RegisterRequest": {
      "title": "RegisterRequest",
      "example": {
        "name": "user",
        "email": "user2@mail.com",
        "password": "user1234",
        "role": "user"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "password",
        "role"
      ]
    },
    "loginrequest": {
      "title": "loginrequest",
      "example": {
        "email": "user@mail.com",
        "password": "user1234"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "userrequest": {
      "title": "userrequest",
      "example": {
        "name": "adi",
        "email": "adi@mail.com",
        "role": "user"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "role": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "email",
        "role"
      ]
    },
    "rolerequest": {
      "title": "rolerequest",
      "example": {
        "name": "dije"
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        }
      },
      "required": [
        "name"
      ]
    },
    "userprofilerequest": {
      "title": "userprofilerequest",
      "example": {
        "provinsi": "Jawa Barat",
        "kota": "Bandung",
        "kecamatan": "Gedebage",
        "kelurahan": "Cimincrang"
      },
      "type": "object",
      "properties": {
        "provinsi": {
          "type": "string"
        },
        "kota": {
          "type": "string"
        },
        "kecamatan": {
          "type": "string"
        },
        "kelurahan": {
          "type": "string"
        }
      },
      "required": [
        "provinsi",
        "kota",
        "kecamatan",
        "kelurahan"
      ]
    },
    "activityrequest": {
      "title": "activityrequest",
      "example": {
        "activity": "Rakernas Dadakan",
        "place": "Aula Gedung E",
        "time": "2023-01-03T08:00:00.007Z"
      },
      "type": "object",
      "properties": {
        "activity": {
          "type": "string"
        },
        "place": {
          "type": "string"
        },
        "time": {
          "type": "string"
        }
      },
      "required": [
        "activity",
        "place",
        "time"
      ]
    }
  },
  "security": [],
  "tags": [
    {
      "name": "auth lokal"
    },
    {
      "name": "user lokal"
    },
    {
      "name": "role lokal"
    },
    {
      "name": "news lokal"
    },
    {
      "name": "user profile lokal"
    },
    {
      "name": "wilayah lokal"
    },
    {
      "name": "activity lokal"
    }
  ]
}
`